<<<<<<< HEAD
import { Header } from '@/Components/Header'
import './globals.css'
import { Saira } from 'next/font/google'

const saira = Saira({ 
  weight: ['300','400','500','600'],
  subsets: ['latin'] })
=======
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
>>>>>>> cc64fdd513d35749e68e3c15dbf4e2a777c3511b

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body className={saira.className}>
        <Header />
        {children}
      </body>
=======
      <body className={inter.className}>{children}</body>
>>>>>>> cc64fdd513d35749e68e3c15dbf4e2a777c3511b
    </html>
  )
}
